[general]

# https://github.com/alacritty/alacritty-theme
# enfocado_dark, enfocado_light
# catppuccin_mocha, catppuccin_latte
import = [
  "catppuccin_mocha.toml",
]

[font]
normal = { family = "monoterm" }
size = 13

[window]
# opacity = 0.9
